"""Initial migration

Revision ID: 4337b7c5065d
Revises: 
Create Date: 2025-12-29 14:26:09.942286

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4337b7c5065d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('opc_id', sa.String(length=255), nullable=False),
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='conversation_pkey')
    )
    op.create_table('llm_run_logs',
    sa.Column('trace_id', sa.String(length=255), nullable=False, comment='对应业务字段 opc_id'),
    sa.Column('conversation_id', models.types.StringUUID(), nullable=False),
    sa.Column('message_id', models.types.StringUUID(), nullable=False),
    sa.Column('inputs', models.types.LongText(), nullable=False),
    sa.Column('outputs', models.types.LongText(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False, comment='运行状态 success / failed / running '),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True, comment='LLM 调用耗时（秒）'),
    sa.Column('hospital_guid', sa.String(length=255), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('error', models.types.LongText(), nullable=True),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='llm_run_log_pkey')
    )
    op.create_table('messages',
    sa.Column('conversation_id', models.types.StringUUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('llm_run_logs')
    op.drop_table('conversations')
    # ### end Alembic commands ###
