"""change some fields

Revision ID: e13bc0e664b1
Revises: 62975dce2d2b
Create Date: 2025-12-30 17:07:46.709407

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13bc0e664b1'
down_revision = '62975dce2d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_run_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tokensss', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_run_logs', schema=None) as batch_op:
        batch_op.drop_column('total_tokensss')

    # ### end Alembic commands ###
