"""change some fields

Revision ID: e5d8f5b988f0
Revises: e13bc0e664b1
Create Date: 2025-12-30 17:08:47.856510

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d8f5b988f0'
down_revision = 'e13bc0e664b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_run_logs', schema=None) as batch_op:
        batch_op.drop_column('total_tokensss')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_run_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tokensss', sa.BIGINT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
