"""make some changes to account and create setup table

Revision ID: 1fb7a0bf1353
Revises: 5cd89bdd7f1c
Create Date: 2026-01-12 14:54:06.153326

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb7a0bf1353'
down_revision = '5cd89bdd7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setups',
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('setup_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('version', name='app_setup_pkey')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interface_language', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('initialized_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('initialized_at')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('timezone')
        batch_op.drop_column('interface_language')

    op.drop_table('app_setups')
    # ### end Alembic commands ###
