"""add message_kind field to message table

Revision ID: 5cd89bdd7f1c
Revises: 58723fd3fc17
Create Date: 2026-01-04 16:45:52.832344

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd89bdd7f1c'
down_revision = '58723fd3fc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_kind', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('message_kind')

    # ### end Alembic commands ###
